### ISSUE TITLE
IoT.js debug build not supported

### ISSUE THREAD

**Issue by tosyu** [rtakacs/remote-testrunner#12]
```bash
python driver.py --app iotjs --buildtype debug --device rpi2 --os linux --username pi --address xxx.xxx.xxx.xxx --remote-path /home/pi/iotjs_tests
[Failed - sftp] [Errno 2] No such file or directory: '/home/tosyu/Projects/remote-testrunner/projects/iotjs/build/arm-linux/release/bin/iotjs'
```

This is due `paths.pyc` having static strings for iotjs

https://github.com/rtakacs/remote-testrunner/blob/master/API/common/paths.py#L90

**Comment by rtakacs** [comment]
The build for RPi devices always debug, so you don't need to specify that. 

https://github.com/rtakacs/remote-testrunner/blob/master/API/application/iotjs.py#L159

The `--buildtype` switch is rather for stm32f4 devices where release is used for testing, and debug is used for debugging (compile IoT.js and NuttX in debug mode). But you are right, I will fix this case.
